# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/google-mpf-5txkh4agy9c2/locations/us-central1/spaces/default-space/applicationTemplates/gcs-bucket-simple

module "cloud-storage-1" {
  source        = "github.com/terraform-google-modules/terraform-google-cloud-storage//modules/simple_bucket?ref=v12.3.0"
  project_id    = var.cloud-storage-1_project_id
  location      = var.cloud-storage-1_location
  name          = var.cloud-storage-1_name
  storage_class = "STANDARD"
}
module "apphub" {
  source         = "github.com/GoogleCloudPlatform/terraform-google-apphub?ref=v0.4.0"
  project_id     = var.apphub_project_id
  location       = var.apphub_location
  service_uris   = [module.cloud-storage-1.apphub_service_uri]
  application_id = var.apphub_application_id
}
