# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/google-mpf-5txkh4agy9c2/locations/us-central1/spaces/default-space/applicationTemplates/gcs-bucket-simple

variable "cloud-storage-1_project_id" {
  description = "The ID of the project to create the bucket in."
  type = string
}
variable "cloud-storage-1_location" {
  description = "The location of the bucket. See https://cloud.google.com/storage/docs/locations."
  type = string
}
variable "cloud-storage-1_name" {
  description = "The name of the bucket."
  type = string
}
variable "apphub_project_id" {
  description = "The project ID of the host project where AppHub application is created."
  type = string
}
variable "apphub_location" {
  description = "The location of AppHub application."
  type = string
}
variable "apphub_application_id" {
  description = "The AppHub application identifier"
  type = string
}
